
const ConversionService = {
  convert: (value, fromUnit, toUnit) => {
    const conversions = {
      temperature: {
        celsius: {
          fahrenheit: value => (value * 9/5) + 32,
          kelvin: value => value + 273.15,
        },
        fahrenheit: {
          celsius: value => (value - 32) * 5/9,
          kelvin: value => (value + 459.67) * 5/9,
        },
        kelvin: {
          celsius: value => value - 273.15,
          fahrenheit: value => (value * 9/5) - 459.67,
        },
      },
      length: {
        meter: {
          centimeter: value => value * 100,
          millimeter: value => value * 1000,
          kilometer: value => value / 1000,
          inch: value => value * 39.3701,
          foot: value => value * 3.28084,
          yard: value => value * 1.09361,
          mile: value => value / 1609.344,
        },
        centimeter: {
          meter: value => value / 100,
          millimeter: value => value * 10,
          kilometer: value => value / 100000,
          inch: value => value / 2.54,
          foot: value => value / 30.48,
          yard: value => value / 91.44,
          mile: value => value / 160934.4,
        },
        millimeter: {
          meter: value => value / 1000,
          centimeter: value => value / 10,
          kilometer: value => value / 1000000,
          inch: value => value / 25.4,
          foot: value => value / 304.8,
          yard: value => value / 914.4,
          mile: value => value / 1609344,
        },
        kilometer: {
          meter: value => value * 1000,
          centimeter: value => value * 100000,
          millimeter: value => value * 1000000,
          inch: value => value * 39370.1,
          foot: value => value * 3280.84,
          yard: value => value * 1093.61,
          mile: value => value / 1.609,
        },
        inch: {
          meter: value => value / 39.3701,
          centimeter: value => value * 2.54,
          millimeter: value => value * 25.4,
          kilometer: value => value / 39370.1,
          foot: value => value / 12,
          yard: value => value / 36,
          mile: value => value / 63360,
        },
        foot: {
          meter: value => value / 3.28084,
          centimeter: value => value * 30.48,
          millimeter: value => value * 304.8,
          kilometer: value => value / 3280.84,
          inch: value => value * 12,
          yard: value => value / 3,
          mile: value => value / 5280,
        },
        yard: {
          meter: value => value / 1.09361,
          centimeter: value => value * 91.44,
          millimeter: value => value * 914.4,
          kilometer: value => value / 1093.61,
            inch: value => value * 36,
            foot: value => value * 3,
            mile: value => value / 1760,
        },
        mile: { 
          meter: value => value * 1609.344,
          centimeter: value => value * 160934.4,
          millimeter: value => value * 1609344,
          kilometer: value => value * 1.609,
          inch: value => value * 63360,
          foot: value => value * 5280,
          yard: value => value * 1760,
        },
        },
        volume: {
          liter: {
            milliliter: value => value * 1000,
            gallon: value => value / 3.785,
            quart: value => value * 1.057,
            pint: value => value * 2.113,
            cup: value => value * 4.227,
            fluid_ounce: value => value * 33.814,
            tablespoon: value => value * 67.628,
            teaspoon: value => value * 202.884,
          }, 
          milliliter: {
            liter: value => value / 1000,
            gallon: value => value / 3785,
            quart: value => value / 946,
            pint: value => value / 473,
            cup: value => value / 240,
            fluid_ounce: value => value / 29.574,
            tablespoon: value => value / 14.787,
            teaspoon: value => value / 4.929,
          },
          gallon: {
            liter: value => value * 3.785,
            milliliter: value => value * 3785,
            quart: value => value * 4,
            pint: value => value * 8,
            cup: value => value * 16,
            fluid_ounce: value => value * 128,
            tablespoon: value => value * 256,
            teaspoon: value => value * 768,
          },
          quart: {
            liter: value => value / 1.057,
            milliliter: value => value * 946.353,
            gallon: value => value / 4,
            pint: value => value * 2,
            cup: value => value * 4,
            fluid_ounce: value => value * 32,
            tablespoon: value => value * 64,
            teaspoon: value => value * 192,
          },
          pint: {
            liter: value => value / 2.113,
            milliliter: value => value * 473.176,
            gallon: value => value / 8,
            quart: value => value / 2,
            cup: value => value * 2,
            fluid_ounce: value => value * 16,
            tablespoon: value => value * 32,
            teaspoon: value => value * 96,
          },
          cup: {
            liter: value => value / 4.227,
            milliliter: value => value * 240,
            gallon: value => value / 16,
            quart: value => value / 4,
            pint: value => value / 2,
            fluid_ounce: value => value * 8,
            tablespoon: value => value * 16,
            teaspoon: value => value * 48,
          },
          fluid_ounce: {
            liter: value => value / 33.814,
            milliliter: value => value * 29.574,
            gallon: value => value / 128,
            quart: value => value / 32,
            pint: value => value / 16,
            cup: value => value / 8,
            tablespoon: value => value * 2,
            teaspoon: value => value * 6,
          },
          tablespoon: {
            liter: value => value / 67.628,
            milliliter: value => value * 14.787,
            gallon: value => value / 256,
            quart: value => value / 64,
            pint: value => value / 32,
            cup: value => value / 16,
            fluid_ounce: value => value / 2,
            teaspoon: value => value * 3,
          },
          teaspoon: {
            liter: value => value / 202.884,
            milliliter: value => value * 4.929,
            gallon: value => value / 768,
            quart: value => value / 192,
            pint: value => value / 96,
            cup: value => value / 48,
            fluid_ounce: value => value / 6,
            tablespoon: value => value / 3,
          },
        },
        mass: {
          kilogram: {
            gram: value => value * 1000,
            milligram: value => value * 1000000,
            tonne: value => value / 907,
            pound: value => value * 2.205,
            ounce: value => value * 35.274,
          },
          gram: {
            kilogram: value => value / 1000,
            milligram: value => value * 1000,
            tonne: value => value / 907185,
            pound: value => value / 454,
            ounce: value => value / 28.35,
          },
          milligram: {
            kilogram: value => value / 1000000,
            gram: value => value / 1000,
            tonne: value => value / 907200000,
            pound: value => value / 453592,
            ounce: value => value / 28350,
          },
          tonne: {
            kilogram: value => value * 907,
            gram: value => value * 907185,
            milligram: value => value * 907200000,
            pound: value => value * 2000,
            ounce: value => value * 32000,
          },
          pound: {
            kilogram: value => value / 2.205,
            gram: value => value * 454,
            milligram: value => value * 453592,
            tonne: value => value / 2000,
            ounce: value => value * 16,
          },
          ounce: {
            kilogram: value => value / 35.274,
            gram: value => value * 28.35,
            milligram: value => value * 28350,
            tonne: value => value / 32000,
            pound: value => value / 16,
          },
        },
  
        speed : {
          meter_per_second: {
            kilometer_per_hour: value => value * 3.6,
            mile_per_hour: value => value * 2.237,
            knot: value => value * 1.944,
          },
          kilometer_per_hour: {
            meter_per_second: value => value / 3.6,
            mile_per_hour: value => value / 1.609,
            knot: value => value / 1.852,
          },
          mile_per_hour: {
            meter_per_second: value => value / 2.237,
            kilometer_per_hour: value => value * 1.609,
            knot: value => value / 1.151,
          },
          knot: {
            meter_per_second: value => value / 1.944,
            kilometer_per_hour: value => value * 1.852,
            mile_per_hour: value => value * 1.151,
          },
        },
        time : {
          second: {
            millisecond: value => value * 1000,
            minute: value => value / 60,
            hour: value => value / 3600,
            day: value => value / 86400,
            week: value => value / 604800,
            month: value => value / 2628000,
            year: value => value / 31540000,
          },
          millisecond: {
            second: value => value / 1000,
            minute: value => value / 60000,
            hour: value => value / 3600000,
            day: value => value / 86400000,
            week: value => value / 604800000,
            month: value => value / 2628000000,
            year: value => value / 31540000000,
          },
          minute: {
            second: value => value * 60,
            millisecond: value => value * 60000,
            hour: value => value / 60,
            day: value => value / 1440,
            week: value => value / 10080,
            month: value => value / 43800,
            year: value => value / 525600,
          },
          hour: {
            second: value => value * 3600,
            millisecond: value => value * 3600000,
            minute: value => value * 60,
            day: value => value / 24,
            week: value => value / 168,
            month: value => value / 730,
            year: value => value / 8760,
          },
          day: {
            second: value => value * 86400,
            millisecond: value => value * 86400000,
            minute: value => value * 1440,
            hour: value => value * 24,
            week: value => value / 7,
            month: value => value / 30.417,
            year: value => value / 365,
          },
          week: {
            second: value => value * 604800,
            millisecond: value => value * 604800000,
            minute: value => value * 10080,
            hour: value => value * 168,
            day: value => value * 7,
            month: value => value / 4.345,
            year: value => value / 52.143,
          },
          month: {
            second: value => value * 2628000,
            millisecond: value => value * 2628000000,
            minute: value => value * 43800,
            hour: value => value * 730,
            day: value => value * 30.417,
            week: value => value * 4.345,
            year: value => value / 12,
          },
          year: {
            second: value => value * 31540000,
            millisecond: value => value * 31540000000,
            minute: value => value * 525600,
            hour: value => value * 8760,
            day: value => value * 365,
            week: value => value * 52.143,
            month: value => value * 12,
          },
        },
        pressure : {
          pascal: {
            kilopascal: value => value / 1000,
            bar: value => value / 100000,
            psi: value => value / 6895,
            torr: value => value / 133,
            atmosphere: value => value / 101325,
          },
          kilopascal: {
            pascal: value => value * 1000,
            bar: value => value / 100,
            psi: value => value / 6.895,
            torr: value => value * 7.501,
            atmosphere: value => value / 101,
          },
          bar: {
            pascal: value => value * 100000,
            kilopascal: value => value * 100,
            psi: value => value * 14.504,
            torr: value => value * 750.062,
            atmosphere: value => value / 1.013,
          },
          psi: {
            pascal: value => value * 6895,
            kilopascal: value => value * 6.895,
            bar: value => value / 14.504,
            torr: value => value * 51.715,
            atmosphere: value => value / 14.696,
          },
          torr: {
            pascal: value => value * 133,
            kilopascal: value => value / 7.501,
            bar: value => value / 750.062,
            psi: value => value / 51.715,
            atmosphere: value => value / 760,
          },
          atmosphere: {
            pascal: value => value * 101325,
            kilopascal: value => value * 101,
            bar: value => value * 1.013,
            psi: value => value * 14.696,
            torr: value => value * 760,
          },
        },
        digital : {
          bit: {
            byte: value => value / 8,
            kilobit: value => value / 1000,
            kilobyte: value => value / 8000,
            megabit: value => value / 1e+6,
            megabyte: value => value / 8e+6,
            gigabit: value => value / 1e+9,
            gigabyte: value => value / 8e+9,
            terabit: value => value / 1e+12,
            terabyte: value => value / 8e+12,
            petabit: value => value / 1e+15,
            petabyte: value => value / 8e+15,
            exabit: value => value / 1e+18,
            exabyte: value => value / 8e+18,
            zettabit: value => value / 1e+21,
            zettabyte: value => value / 8e+21,
            yottabit: value => value / 1e+24,
            yottabyte: value => value / 8e+24,
          },
          byte: {
            bit: value => value * 8,
            kilobit: value => value / 125,
            kilobyte: value => value / 1000,
            megabit: value => value / 125000,
            megabyte: value => value / 1e+6,
            gigabit: value => value / 1.25e+8,
            gigabyte: value => value / 1e+9,
            terabit: value => value / 1.25e+11,
            terabyte: value => value / 1e+12,
            petabit: value => value / 1.25e+14,
            petabyte: value => value / 1e+15,
            exabit: value => value / 1.25e+17,
            exabyte: value => value / 1e+18,
            zettabit: value => value / 1.25e+20,
            zettabyte: value => value / 1e+21,
            yottabit: value => value / 1.25e+23,
            yottabyte: value => value / 1e+24,
          },
          kilobit: {
            bit: value => value * 1000,
            byte: value => value * 125,
            kilobyte: value => value / 8,
            megabit: value => value / 1000,
            megabyte: value => value / 8000,
            gigabit: value => value / 1e+6,
            gigabyte: value => value / 8e+6,
            terabit: value => value / 1e+9,
            terabyte: value => value / 8e+9,
            petabit: value => value / 1e+12,
            petabyte: value => value / 8e+12,
            exabit: value => value / 1e+15,
            exabyte: value => value / 8e+15,
            zettabit: value => value / 1e+18,
            zettabyte: value => value / 8e+18,
            yottabit: value => value / 1e+21,
            yottabyte: value => value / 8e+21,
          },
          kilobyte: {
            bit: value => value * 8000,
            byte: value => value * 1000,
            kilobit: value => value * 8,
            megabit: value => value / 125,
            megabyte: value => value / 1000,
            gigabit: value => value / 125000,
            gigabyte: value => value / 1e+6,
            terabit: value => value / 1.25e+8,
            terabyte: value => value / 1e+9,
            petabit: value => value / 1.25e+11,
            petabyte: value => value / 1e+12,
            exabit: value => value / 1.25e+14,
            exabyte: value => value / 1e+15,
            zettabit: value => value / 1.25e+17,
            zettabyte: value => value / 1e+18,
            yottabit: value => value / 1.25e+20,
            yottabyte: value => value / 1e+21,
          },
          megabit: {
            bit: value => value * 1e+6,
            byte: value => value * 125000,
            kilobit: value => value * 1000,
            kilobyte: value => value * 125,
            megabyte: value => value / 8,
            gigabit: value => value / 1000,
            gigabyte: value => value / 8000,
            terabit: value => value / 1e+6,
            terabyte: value => value / 8e+6,
            petabit: value => value / 1e+9,
            petabyte: value => value / 8e+9,
            exabit: value => value / 1e+12,
            exabyte: value => value / 8e+12,
            zettabit: value => value / 1e+15,
            zettabyte: value => value / 8e+15,
            yottabit: value => value / 1e+18,
            yottabyte: value => value / 8e+18,
          },
          megabyte: {
            bit: value => value * 8e+6,
            byte: value => value * 1e+6,
            kilobit: value => value * 8000,
            kilobyte: value => value * 1000,
            megabit: value => value * 8,
            gigabit: value => value / 125,
            gigabyte: value => value / 1000,
            terabit: value => value / 125000,
            terabyte: value => value / 1e+6,
            petabit: value => value / 1.25e+8,
            petabyte: value => value / 1e+9,
            exabit: value => value / 1.25e+11,
            exabyte: value => value / 1e+12,
            zettabit: value => value / 1.25e+14,
            zettabyte: value => value / 1e+15,
            yottabit: value => value / 1.25e+17,
            yottabyte: value => value / 1e+18,
          },
          gigabit: {
            bit: value => value * 1e+9,
            byte: value => value * 1.25e+8,
            kilobit: value => value * 1e+6,
            kilobyte: value => value * 125000,
            megabit: value => value * 1000,
            megabyte: value => value * 125,
            gigabyte: value => value / 8,
            terabit: value => value / 1000,
            terabyte: value => value / 8000,
            petabit: value => value / 1e+6,
            petabyte: value => value / 8e+6,
            exabit: value => value / 1e+9,
            exabyte: value => value / 8e+9,
            zettabit: value => value / 1e+12,
            zettabyte: value => value / 8e+12,
            yottabit: value => value / 1e+15,
            yottabyte: value => value / 8e+15,
          },
          gigabyte: {
            bit: value => value * 8e+9,
            byte: value => value * 1e+9,
            kilobit: value => value * 8e+6,
            kilobyte: value => value * 1e+6,
            megabit: value => value * 8000,
            megabyte: value => value * 1000,
            gigabit: value => value * 8,
            terabit: value => value / 125,
            terabyte: value => value / 1000,
            petabit: value => value / 125000,
            petabyte: value => value / 1e+6,
            exabit: value => value / 1.25e+8,
            exabyte: value => value / 1e+9,
            zettabit: value => value / 1.25e+11,
            zettabyte: value => value / 1e+12,
            yottabit: value => value / 1.25e+14,
            yottabyte: value => value / 1e+15,
          },
          terabit: {
            bit: value => value * 1e+12,
            byte: value => value * 1.25e+11,
            kilobit: value => value * 1e+9,
            kilobyte: value => value * 1.25e+8,
            megabit: value => value * 1e+6,
            megabyte: value => value * 125000,
            gigabit: value => value * 1000,
            gigabyte: value => value * 125,
            terabyte: value => value / 8,
            petabit: value => value / 1000,
            petabyte: value => value / 8000,
            exabit: value => value / 1e+6,
            exabyte: value => value / 8e+6,
            zettabit: value => value / 1e+9,
            zettabyte: value => value / 8e+9,
            yottabit: value => value / 1e+12,
            yottabyte: value => value / 8e+12,
          },
          terabyte: {
            bit: value => value * 8e+12,
            byte: value => value * 1e+12,
            kilobit: value => value * 8e+9,
            kilobyte: value => value * 1e+9,
            megabit: value => value * 8e+6,
            megabyte: value => value * 1e+6,
            gigabit: value => value * 8000,
            gigabyte: value => value * 1000,
            terabit: value => value * 8,
            petabit: value => value / 125,
            petabyte: value => value / 1000,
            exabit: value => value / 125000,
            exabyte: value => value / 1e+6,
            zettabit: value => value / 125000000,
            zettabyte: value => value / 1e+9,
            yottabit: value => value / 1.25e+11,
            yottabyte: value => value / 1e+12,
          },
          petabit: {
            bit: value => value * 1e+15,
            byte: value => value * 1.25e+14,
            kilobit: value => value * 1e+12,
            kilobyte: value => value * 1.25e+11,
            megabit: value => value * 1e+9,
            megabyte: value => value * 1.25e+8,
            gigabit: value => value * 1e+6,
            gigabyte: value => value * 125000,
            terabit: value => value * 1000,
            terabyte: value => value * 125,
            petabyte: value => value / 8,
            exabit: value => value / 1000,
            exabyte: value => value / 8000,
            zettabit: value => value / 1e+6,
            zettabyte: value => value / 8e+6,
            yottabit: value => value / 1e+9,
            yottabyte: value => value / 8e+9,
          },
          petabyte: {
            bit: value => value * 8e+15,
            byte: value => value * 1e+15,
            kilobit: value => value * 8e+12,
            kilobyte: value => value * 1e+12,
            megabit: value => value * 8e+9,
            megabyte: value => value * 1e+9,
            gigabit: value => value * 8e+6,
            gigabyte: value => value * 1e+6,
            terabit: value => value * 8000,
            terabyte: value => value * 1000,
            petabit: value => value * 8,
            exabit: value => value / 125,
            exabyte: value => value / 1000,
            zettabit: value => value / 125000,
            zettabyte: value => value / 1e+6,
            yottabit: value => value / 125000000,
            yottabyte: value => value / 1e+9,
          },
          exabit: {
            bit: value => value * 1e+18,
            byte: value => value * 1.25e+17,
            kilobit: value => value * 1e+15,
            kilobyte: value => value * 1.25e+14,
            megabit: value => value * 1e+12,
            megabyte: value => value * 1.25e+11,
            gigabit: value => value * 1e+9,
            gigabyte: value => value * 1.25e+8,
            terabit: value => value * 1000,
            terabyte: value => value * 125,
            petabit: value => value * 8,
            petabyte: value => value * 1000,
            exabyte: value => value / 8,
            zettabit: value => value / 125,
            zettabyte: value => value / 1000,
            yottabit: value => value / 125000,
            yottabyte: value => value / 1000000,
          },
          exabyte: {
            bit: value => value * 8e+18,
            byte: value => value * 1e+18,
            kilobit: value => value * 8e+15,
            kilobyte: value => value * 1e+15,
            megabit: value => value * 8e+12,
            megabyte: value => value * 1e+12,
            gigabit: value => value * 8e+9,
            gigabyte: value => value * 1e+9,
            terabit: value => value * 8e+6,
            terabyte: value => value * 1e+6,
            petabit: value => value * 8e+3,
            petabyte: value => value * 1000,
            exabit: value => value * 8,
            zettabit: value => value / 125,
            zettabyte: value => value / 1000,
            yottabit: value => value / 125000,
            yottabyte: value => value / 1e+6,
          },
          zettabit: {
            bit: value => value * 1e+21,
            byte: value => value * 1.25e+20,
            kilobit: value => value * 1e+18,
            kilobyte: value => value * 1.25e+17,
            megabit: value => value * 1e+15,
            megabyte: value => value * 1.25e+14,
            gigabit: value => value * 1e+12,
            gigabyte: value => value * 1.25e+11,
            terabit: value => value * 1e+9,
            terabyte: value => value * 1.25e+8,
            petabit: value => value * 1000,
            petabyte: value => value * 125,
            exabit: value => value * 8,
            exabyte: value => value * 1000,
            zettabyte: value => value / 8,
            yottabit: value => value / 125,
            yottabyte: value => value / 1000,
          },
          zettabyte: {
            bit: value => value * 8e+21,
            byte: value => value * 1e+21,
            kilobit: value => value * 8e+18,
            kilobyte: value => value * 1e+18,
            megabit: value => value * 8e+15,
            megabyte: value => value * 1e+15,
            gigabit: value => value * 8e+12,
            gigabyte: value => value * 1e+12,
            terabit: value => value * 8e+9,
            terabyte: value => value * 1e+9,
            petabit: value => value * 8e+6,
            petabyte: value => value * 1e+6,
            exabit: value => value * 8e+3,
            exabyte: value => value * 1000,
            zettabit: value => value * 8,
            yottabit: value => value / 125,
            yottabyte: value => value / 1000,
          },
          yottabit: {
            bit: value => value * 1e+24,
            byte: value => value * 1.25e+23,
            kilobit: value => value * 1e+21,
            kilobyte: value => value * 1.25e+20,
            megabit: value => value * 1e+18,
            megabyte: value => value * 1.25e+17,
            gigabit: value => value * 1e+15,
            gigabyte: value => value * 1.25e+14,
            terabit: value => value * 1e+12,
            terabyte: value => value * 1.25e+11,
            petabit: value => value * 1e+9,
            petabyte: value => value * 1.25e+8,
            exabit: value => value * 1000,
            exabyte: value => value * 125,
            zettabit: value => value * 8,
            zettabyte: value => value * 1000,
            yottabyte: value => value / 8,
          },
          yottabyte: {
            bit: value => value * 8e+24,
            byte: value => value * 1e+24,
            kilobit: value => value * 8e+21,
            kilobyte: value => value * 1e+21,
            megabit: value => value * 8e+18,
            megabyte: value => value * 1e+18,
            gigabit: value => value * 8e+15,
            gigabyte: value => value * 1e+15,
            terabit: value => value * 8e+12,
            terabyte: value => value * 1e+12,
            petabit: value => value * 8e+9,
            petabyte: value => value * 1e+9,
            exabit: value => value * 8e+6,
            exabyte: value => value * 1000,
            zettabit: value => value * 8e+3,
            zettabyte: value => value * 1000,
          },
        },
        
        energy : {
          joule: {
            kilojoule: value => value / 1000,
            gram_calorie: value => value / 4.184,
            kilocalorie: value => value / 4184,
            watt_hour: value => value / 3600,
            kilowatt_hour: value => value / 3600000,
            electronvolt: value => value * 6.242e+18,
            british_thermal_unit: value => value / 1055,
            us_therm: value => value / 105480400,
            foot_pound: value => value / 1.356,
          },
          kilojoule: {
            joule: value => value * 1000,
            gram_calorie: value => value * 239,
            kilocalorie: value => value / 4.184,
            watt_hour: value => value / 3.6,
            kilowatt_hour: value => value / 3600,
            electronvolt: value => value * 6.242e+21,
            british_thermal_unit: value => value / 1.055,
            us_therm: value => value / 105480400000,
            foot_pound: value => value * 738,
          },
          gram_calorie: {
            joule: value => value * 4.184,
            kilojoule: value => value / 239,
            kilocalorie: value => value / 1000,
            watt_hour: value => value / 860,
            kilowatt_hour: value => value / 860421,
            electronvolt: value => value * 2.611e+19,
            british_thermal_unit: value => value / 252,
            us_therm: value => value / 252164400,
            foot_pound: value => value * 3.086,
          },
          kilocalorie: {
            joule: value => value * 4184,
            kilojoule: value => value * 4.184,
            gram_calorie: value => value * 1000,
            watt_hour: value => value / 0.860,
            kilowatt_hour: value => value / 860,
            electronvolt: value => value * 2.611e+22,
            british_thermal_unit: value => value * 3.966,
            us_therm: value => value / 2521644,
            foot_pound: value => value * 3086,
          },
          watt_hour: {
            joule: value => value * 3600,
            kilojoule: value => value * 3.6,
            gram_calorie: value => value * 860,
            kilocalorie: value => value * 0.860,
            kilowatt_hour: value => value / 1000,
            electronvolt: value => value * 2.247e+22,
            british_thermal_unit: value => value * 3.412,
            us_therm: value => value / 29300,
            foot_pound: value => value * 2655,
          },
          kilowatt_hour: {
            joule: value => value * 3600000,
            kilojoule: value => value * 3600,
            gram_calorie: value => value * 860421,
            kilocalorie: value => value * 860,
            watt_hour: value => value * 1000,
            electronvolt: value => value * 2.247e+25,
            british_thermal_unit: value => value * 3412,
            us_therm: value => value / 29.307,
            foot_pound: value => value * 2.655e+6,
          },
          electronvolt: {
            joule: value => value / 6.242e+18,
            kilojoule: value => value / 6.242e+21,
            gram_calorie: value => value / 2.611e+19,
            kilocalorie: value => value / 2.611e+22,
            watt_hour: value => value / 2.247e+22,
            kilowatt_hour: value => value / 2.247e+25,
            british_thermal_unit: value => value / 2.931e+19,
            us_therm: value => value / 2.931e+22,
            foot_pound: value => value / 8.462e+18,
          },
          british_thermal_unit: {
            joule: value => value * 1055,
            kilojoule: value => value * 1.055,
            gram_calorie: value => value * 252,
            kilocalorie: value => value / 3.966,
            watt_hour: value => value / 3.412,
            kilowatt_hour: value => value * 3412,
            electronvolt: value => value * 2.931e+19,
            us_therm: value => value / 99976,
            foot_pound: value => value * 778,
          },
          us_therm: {
            joule: value => value * 105480400,
            kilojoule: value => value * 105480,
            gram_calorie: value => value * 252164400,
            kilocalorie: value => value * 252164,
            watt_hour: value => value * 29300,
            kilowatt_hour: value => value * 29.307,
            electronvolt: value => value * 2.931e+22,
            british_thermal_unit: value => value * 99976,
            foot_pound: value => value * 7.78e+7,
          },
          foot_pound: {
            joule: value => value * 1.356,
            kilojoule: value => value / 738,
            gram_calorie: value => value / 3.086,
            kilocalorie: value => value / 3086,
            watt_hour: value => value / 2655,
            kilowatt_hour: value => value / 2.655e+6,
            electronvolt: value => value * 8.462e+18,
            british_thermal_unit: value => value / 778,
            us_therm: value => value / 7.78e+7,
          }, 
        },
        angle : {
          degree: {
            radian: value => value * 0.0174533,
            gradian: value => value * 1.11111,
            arcminute: value => value * 60,
            arcsecond: value => value * 3600,
            revolution: value => value / 360,
            quadrant: value => value / 90,
            sextant: value => value / 60,
            sign: value => value / 30,
            mil: value => value * 17.7778,
            turn: value => value / 360,
          },
          radian: {
            degree: value => value / 0.0174533,
            gradian: value => value * 63.6619,
            arcminute: value => value * 3437.75,
            arcsecond: value => value * 206265,
            revolution: value => value / 6.28319,
            quadrant: value => value / 1.5708,
            sextant: value => value / 1.0472,
            sign: value => value / 0.523599,
            mil: value => value * 1018.59,
            turn: value => value / 6.28319,
          },
          gradian: {
            degree: value => value / 1.11111,
            radian: value => value / 63.6619,
            arcminute: value => value * 54,
            arcsecond: value => value * 3240,
            revolution: value => value / 400,
            quadrant: value => value / 100,
            sextant: value => value / 66.6667,
            sign: value => value / 33.3333,
            mil: value => value * 20,
            turn: value => value / 400,
          },
          arcminute: {
            degree: value => value / 60,
            radian: value => value / 3437.75,
            gradian: value => value / 54,
            arcsecond: value => value * 60,
            revolution: value => value / 21600,
            quadrant: value => value / 5400,
            sextant: value => value / 3600,
            sign: value => value / 1800,
            mil: value => value * 3.33333,
            turn: value => value / 21600,
          },
          arcsecond: {
            degree: value => value / 3600,
            radian: value => value / 206265,
            gradian: value => value / 3240,
            arcminute: value => value / 60,
            revolution: value => value / 1296000,
            quadrant: value => value / 324000,
            sextant: value => value / 216000,
            sign: value => value / 108000,
            mil: value => value * 0.0555556,
            turn: value => value / 1296000,
          },
          revolution: {
            degree: value => value * 360,
            radian: value => value * 6.28319,
            gradian: value => value * 400,
            arcminute: value => value * 21600,
            arcsecond: value => value * 1296000,
            quadrant: value => value * 4,
            sextant: value => value * 6,
            sign: value => value * 12,
            mil: value => value * 6400,
            turn: value => value * 360,
          },
          quadrant: {
            degree: value => value * 90,
            radian: value => value * 1.5708,
            gradian: value => value * 100,
            arcminute: value => value * 5400,
            arcsecond: value => value * 324000,
            revolution: value => value / 4,
            sextant: value => value * 1.5,
            sign: value => value * 3,
            mil: value => value * 1600,
            turn: value => value * 90,
          },
          sextant: {
            degree: value => value * 60,
            radian: value => value * 1.0472,
            gradian: value => value * 66.6667,
            arcminute: value => value * 3600,
            arcsecond: value => value * 216000,
            revolution: value => value / 6,
            quadrant: value => value / 1.5,
            sign: value => value * 2,
            mil: value => value * 1066.67,
            turn: value => value * 60,
          },
          sign: {
            degree: value => value * 30,
            radian: value => value * 0.523599,
            gradian: value => value * 33.3333,
            arcminute: value => value * 1800,
            arcsecond: value => value * 108000,
            revolution: value => value / 12,
            quadrant: value => value / 3,
            sextant: value => value / 2,
            mil: value => value * 533.333,
            turn: value => value * 30,
          },
          mil: {
            degree: value => value / 17.7778,
            radian: value => value / 1018.59,
            gradian: value => value / 20,
            arcminute: value => value / 3.33333,
            arcsecond: value => value / 0.0555556,
            revolution: value => value / 6400,
            quadrant: value => value / 1600,
            sextant: value => value / 1066.67,
            sign: value => value / 533.333,
            turn: value => value / 6400,
          },
          turn: {
            degree: value => value * 360,
            radian: value => value * 6.28319,
            gradian: value => value * 400,
            arcminute: value => value * 21600,
            arcsecond: value => value * 1296000,
            revolution: value => value * 360,
            quadrant: value => value * 90,
            sextant: value => value * 60,
            sign: value => value * 120,
            mil: value => value * 6400,
          },
        },
        force : {
          newton: {
            dyne: value => value * 100000,
            gramforce: value => value * 101.972,
            kilogramforce: value => value * 0.101972,
            kipforce: value => value * 0.000224809,
            ounceforce: value => value * 3.596943,
            poundforce: value => value * 0.224809,
            poundal: value => value * 7.233014,
            tonforce: value => value * 0.000101972,
          },
          dyne: {
            newton: value => value / 100000,
            gramforce: value => value * 0.00101972,
            kilogramforce: value => value * 0.00000101972,
            kipforce: value => value * 2.24809e-9,
            ounceforce: value => value * 0.0000359694,
            poundforce: value => value * 0.00000224809,
            poundal: value => value * 0.0000723301,
            tonforce: value => value * 1.01972e-9,
          },
          gramforce: {
            newton: value => value / 101.972,
            dyne: value => value / 0.00101972,
            kilogramforce: value => value * 0.001,
            kipforce: value => value * 0.00000220462,
            ounceforce: value => value * 0.035274,
            poundforce: value => value * 0.00220462,
            poundal: value => value * 0.0709316,
            tonforce: value => value * 0.000001,
          },
          kilogramforce: {
            newton: value => value / 0.101972,
            dyne: value => value / 0.00000101972,
            gramforce: value => value * 1000,
            kipforce: value => value * 0.00220462,
            ounceforce: value => value * 35.274,
            poundforce: value => value * 2.20462,
            poundal: value => value * 70.9316,
            tonforce: value => value * 0.001,
          },
          kipforce: {
            newton: value => value / 0.000224809,
            dyne: value => value / 2.24809e-9,
            gramforce: value => value * 453592,
            kilogramforce: value => value * 453.592,
            ounceforce: value => value * 16000,
            poundforce: value => value * 1000,
            poundal: value => value * 32174.1,
            tonforce: value => value * 0.453592,
          },
          ounceforce: {
            newton: value => value / 3.596943,
            dyne: value => value / 0.0000359694,
            gramforce: value => value * 28.3495,
            kilogramforce: value => value * 0.0283495,
            kipforce: value => value * 0.0000625,
            poundforce: value => value * 0.0625,
            poundal: value => value * 2.01012,
            tonforce: value => value * 0.0000283495,
          },
          poundforce: {
            newton: value => value / 0.224809,
            dyne: value => value / 0.00000224809,
            gramforce: value => value * 453.592,
            kilogramforce: value => value * 0.453592,
            kipforce: value => value * 0.001,
            ounceforce: value => value * 16,
            poundal: value => value * 32.1741,
            tonforce: value => value * 0.000453592,
          },
          poundal: {
            newton: value => value / 7.233014,
            dyne: value => value / 0.0000723301,
            gramforce: value => value * 14.0981,
            kilogramforce: value => value * 0.0140981,
            kipforce: value => value * 0.0000310809,
            ounceforce: value => value * 0.444822,
            poundforce: value => value * 0.0310809,
            tonforce: value => value * 0.0000140981,
          },
          tonforce: {
            newton: value => value / 0.000101972,
            dyne: value => value / 1.01972e-9,
            gramforce: value => value * 1000000,
            kilogramforce: value => value * 1000,
            kipforce: value => value * 2.20462,
            ounceforce: value => value * 35274,
            poundforce: value => value * 2204.62,
            poundal: value => value * 70931.6,
          },
        },
        power : {
          watt: {
            kilowatt : value => value / 1000,
            horsepower : value => value * 0.00134102,
            horsepower_metric : value => value * 0.00135962,
            horsepower_electric : value => value * 0.00134048,
            horsepower_uk : value => value * 0.00134102,
          },
          kilowatt: {
            watt : value => value * 1000,
            horsepower : value => value * 1.34102,
            horsepower_metric : value => value * 1.35962,
            horsepower_electric : value => value * 1.34048,
            horsepower_uk : value => value * 1.34102,
          },
          horsepower: {
            watt : value => value * 745.7,
            kilowatt : value => value * 0.7457,
            horsepower_metric : value => value * 1.01387,
            horsepower_electric : value => value * 0.746,
            horsepower_uk : value => value * 0.7457,
          },
          horsepower_metric: {
            watt : value => value * 735.499,
            kilowatt : value => value * 0.735499,
            horsepower : value => value * 0.98632,
            horsepower_electric : value => value * 0.73549875,
            horsepower_uk : value => value * 0.735499,
          },
          horsepower_electric: {
            watt : value => value * 746,
            kilowatt : value => value * 0.746,
            horsepower : value => value * 1.34048,
            horsepower_metric : value => value * 1.35962,
            horsepower_uk : value => value * 0.746,
          },
          horsepower_uk: {
            watt : value => value * 745.7,
            kilowatt : value => value * 0.7457,
            horsepower : value => value * 1.34102,
            horsepower_metric : value => value * 1.35962,
            horsepower_electric : value => value * 0.746,
          },
        },


            

        };
        return conversions[fromUnit.type][fromUnit.name][toUnit.name](value);
        },
        };
      
        export default ConversionService;
        
